Draft: queryToReadAll
marklogic/node-client-api pull request #634
Opened 2022-01-04 22:14 UTC by anu3990

2022-01-05 20:08 UTC, ehennum requested changes
Feedback provided in email

2022-01-10 19:15 UTC, ehennum reviewed
This update seems headed in the right direction

2022-01-14 20:51 UTC, ehennum reviewed
Other than some suggestions about the conditional testing, this update looks good.

2022-01-14 20:51 UTC, ehennum commented on lib/documents.js
> +        (typeof jobState.jobOptions.consistentSnapshot !== 'object' || !jobState.jobOptions.consistentSnapshot.valueOf('Timestamp'))){
I'd suggest:

    typeof jobState.jobOptions.consistentSnapshot !== 'boolean &&
    !(jobState.jobOptions.consistentSnapshot instanceof Boolean) &&
    !(jobState.jobOptions.consistentSnapshotinstanceof instanceof mlutil.Timestamp)

JavaScript has both primitive and object versions of booleans and numbers (similar to Java), and the constructor of the Timestamp object can be used to verify the type similar to:

https://github.com/marklogic/node-client-api/blob/master/lib/documents.js#L1885

The same comment applies to the other initial validation.

2022-01-14 20:51 UTC, ehennum commented on lib/documents.js
> +  if(jobState.jobOptions.consistentSnapshot && (typeof jobState.jobOptions.consistentSnapshot === 'object')){
A Boolean object would pass this test but not a test using instanceof mlutil.Timestamp

The same comment applies to the other initial validation.

2022-01-14 21:33 UTC, anu3990 commented
Merging all the commits in a single commit after adding all the changes and suggestions.

2022-01-14 21:35 UTC, merged