NODE-31 Deleting Documents. Initialization, Operation, Finalization.
marklogic/node-client-api pull request #668
Opened 2022-03-23 18:10 UTC by AndreiPanti

2022-03-30 18:16 UTC, anu3990 requested changes

2022-03-30 18:16 UTC, anu3990 commented on lib/documents.js
> +*/
Please remove this comment.

2022-03-30 18:16 UTC, anu3990 commented on test-basic/documents-data-movement-removeAllUris.js
> +
Please remove this block if it is not needed.

2022-03-30 18:16 UTC, anu3990 commented on test-basic/documents-data-movement-removeAllUris.js
> +let removePath = './test-basic/data/removeAllUris_remove.js';
Please remove these two variables if they are not needed.

2022-03-30 21:18 UTC, anu3990 approved these changes

2022-03-30 21:18 UTC, anu3990 commented
@AndreiPanti please combine everything into one commit before merging.

2022-04-01 00:55 UTC, georgeajit approved these changes

2022-04-01 10:55 UTC, merged