DEVEXP-72: Upgrade dependencies in Node-client version 2.9.0
marklogic/node-client-api pull request #679
Opened 2022-10-11 08:36 UTC by mariusmarklogic

The tests are working fine:    973 passing (3m)

But the "dicer" package is not solvable because has no good version.

https://github.com/advisories/GHSA-wm7h-9275-46v2

![image](https://user-images.githubusercontent.com/104991743/195040654-80b949e8-a697-464e-82f2-193711749cf6.png)

2022-10-11 18:01 UTC, anu3990 requested changes

2022-10-11 18:01 UTC, anu3990 commented on package.json
> +    "sanitize-html": "^2.7.2"
minimist should be covered when we update kerberos. we should avoid adding a force-resolution since it might create confusions.

2022-10-11 18:03 UTC, anu3990 commented
@mariusmarklogic  Good progress.! Are both the high vulnerabilities in dicer?

2022-10-12 05:36 UTC, mariusmarklogic commented
> 

Yes, the npm audit didn't show me something else as vulnerability, except dicer

2022-10-13 21:29 UTC, closed without merging